name: Functional Tests
description: Run Functional Tests
inputs:
  test-set:
    description: Test set to run
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare tests
      run: |
        tar xfz ./kourou.tgz
        npm install --prefix package --silent --only production
      shell: bash
    - name: Run functional test using cucumber
      run: |
        features/run-kuzzle-stack.sh
        npm run test:functional:${{ inputs.test-set }}
      env:
        KOUROU_RUNTIME: ./package/bin/run"
      shell: bash
