name: Functional Tests
description: Run Functional Tests
inputs:
  test-set:
    description: Test set to run
    required: true
runs:
  using: "composite"
  steps:
    - name: Run functional test
      run: |
        features/run-kuzzle-stack.sh
        npm run test:functional:${{ inputs.test-set }}
      shell: bash
