name: Functional Tests
description: Run Functional Tests
runs:
  using: "composite"
  steps:
    - name: Prepare tests
      run: |
        npm install --silent
        npm pack
        tar xf kourou-$(node -e 'console.log(require("./package.json").version)').tgz
        npm install --prefix package --silent --only production
        rm -rf ./bin
      shell: bash
    - name: Run functional test using cucumber
      run: |
        features/run-kuzzle-stack.sh
        npm run test:functional:cucumber
      env:
        KOUROU_RUNTIME: "./package/bin/run"
      shell: bash
