name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Kourour TS build
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: |
          npm install --silent --unsafe-perm
          npm install --silent --unsafe-perm --only=dev
          npm run prepack

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Kourou Lint
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: |
          npm install --silent --unsafe-perm
          npm install --silent --unsafe-perm --only=dev
          npm run test:lint

  functional-test-stdout:
    runs-on: ubuntu-latest
    needs: build
    env:
      KOUROU_RUNTIME: "./package/bin/run"
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Kourou Functional Stdout Tests
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: |
          npm install --silent --unsafe-perm
          npm pack
          tar xf kourou-$(node -e 'console.log(require("./package.json").version)').tgz
          npm install --prefix package --silent --unsafe-perm --only production
          rm -rf ./bin
          npm run test:functional:stdout

  functional-test-cucumber:
    runs-on: ubuntu-latest
    needs: build
    env:
      KOUROU_RUNTIME: "./package/bin/run"
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v2
      - name: Kourou Functional Cucumber Tests
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: |
          npm install --silent --unsafe-perm
          npm pack
          tar xf kourou-$(node -e 'console.log(require("./package.json").version)').tgz
          npm install --prefix package --silent --unsafe-perm --only production
          rm -rf ./bin
          bash features/run-kuzzle-stack.sh
          npm run test:functional:cucumber
