name: Publish to npm

on: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.ref, "master")
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
